fixing imports
SIRI-CEN/SIRI pull request #108
Opened 2023-04-05 09:17 UTC by ue71603

xmllint has some problems with multiple imports with the same namespace. Fixes a problem in OJP.

2023-04-05 09:30 UTC, skinkie commented on xsd/siri_facilityMonitoring_service.xsd
> + <!-- <xsd:import namespace="http://www.ifopt.org.uk/acsb" schemaLocation="acsb/acsb_passengerMobility.xsd"/>
I suggest not using comments in pull requests.

2023-04-07 07:44 UTC, Aurige commented
Ok for me, but is it expected to also have this huge reformatting of some of the files ? That probably means that SIRI also requires that xmllint pretty action that was applied on OJP and NeTEx

2023-04-07 10:24 UTC, ue71603 commented
@Aurige At some point I think we will need to do the reformatting. If we wish to use the same github actions.
Best therfore to minimize the number of PR in github.

2023-04-07 10:25 UTC, ue71603 commented
or the current rule, if it exists needs to be incorporated into the action.

2023-04-07 10:26 UTC, skinkie commented
One step at a time. Migrating to github actions would be something separate.

2023-04-15 14:32 UTC, Aurige approved these changes

2023-05-25 10:06 UTC, AndreasAtSBB approved these changes
Removed some imports, removed prefixes ojp: and siri:.
Schould now compile.

2023-05-25 13:31 UTC, sgrossberndt requested changes
This PR is broken as @ue71603 simply backported the changes done to OJP to SIRI, but in https://github.com/VDVde/OJP/commit/241cf4b7d812dad4251da4116376c6c3fe532978, where SIRI was updated to 2.1 he changed the file names of the ifopt files and removed the version numbers there, while they still have them here.

Also as mentioned before the imports should not be commented out but adapted.

2023-05-25 14:16 UTC, sgrossberndt approved these changes

2023-05-25 14:17 UTC, sgrossberndt commented
Is the Travis integration broken for SIRI?

2023-05-25 14:18 UTC, skinkie commented
> Is the Travis integration broken for SIRI?

I think everything was broken due to credits etc.

2023-06-21 15:31 UTC, merged