Documentation - Enhancement Readme
SIRI-CEN/SIRI pull request #126
Opened 2023-11-07 07:50 UTC by EliotTerrier

**Creation of a README:** 
- Main directory functionalities.
- Version summary table. 

@skinkie @Aurige for your review

2023-11-07 08:05 UTC, skinkie commented
Postpone merge until wiki related issues are sorted.

2024-03-20 12:46 UTC, ue71603 approved these changes

2024-03-20 13:30 UTC, skinkie commented on README.md
> +Further information on the examples is available on the [wiki](https://github.com/ITxPT/SIRI/wiki/Using-SIRI#how-to-use-example-files)
This should be part of this repo.

2024-03-20 13:30 UTC, skinkie commented on README.md
> +More information on the tools available for working with SIRI XML schema can be found in the [wiki](https://github.com/ITxPT/SIRI/wiki/Software-&-tools)
This should be part of this repo.

2024-03-20 14:17 UTC, ue71603 commented
@EliotTerrier  I can't rebase your PR. Can  you rebase it to the current master?

2025-05-27 16:01 UTC, haeckerbaer approved these changes

2025-05-27 16:03 UTC, haeckerbaer requested changes
Please see comments from skinkie

2025-06-27 08:57 UTC, TuThoThai commented
As of 27 June 2025, @TuThoThai to rework it completely and make sure external references are stable links.

2025-10-30 10:33 UTC, closed without merging