SIRI FM - Site filter addition
SIRI-CEN/SIRI pull request #54
Opened 2020-08-26 15:31 UTC by Aurige

Complement to CR71 to be able to filter by Site in SIRI FM (SITE generalisation was introduced by Transmodel after the definition of SIRI FM, and only STOP PLACE and STOP PLACE COMPONENT were the only SITE related available filters at that time).

2020-09-15 07:39 UTC, haeckerbaer commented
See also parent https://github.com/SIRI-CEN/SIRI/pull/43

2020-09-15 08:10 UTC, hennoit requested changes
Type of element _SiteRef_ should be _siteRefStructure_ (with a **lowercase s**). See the complaint by the automatic build.

2020-09-15 09:38 UTC, haeckerbaer commented on xsd/siri_model/siri_reference-v2.0.xsd
> +<xsd:complexType name="siteRefStructure">
should be upper case "SiteRefStructure"

2020-10-20 08:54 UTC, hennoit approved these changes

2020-12-15 11:08 UTC, haeckerbaer approved these changes

2020-12-15 11:11 UTC, merged