CR075/078: rename schema files, update status/version and clean-up
SIRI-CEN/SIRI pull request #66
Opened 2020-11-04 17:46 UTC by haeckerbaer

CR according to master list and SG7 Meeting on 15.9.2020.

2021-02-02 12:11 UTC, hennoit approved these changes

2021-02-10 10:10 UTC, prirey requested changes
Hi Adrian, can you integrate the new XML Schema Reference from https://github.com/SIRI-CEN/SIRI/pull/47 in this CR?
I will close Pullrequest 47 as discussed (all other UmS needs are integrated in UmS - CEN Sync).

2021-03-09 08:52 UTC, tim-rivett commented on xsd/acsb/acsb_limitations.xsd
> +    <Status>Version 2.1 Draft</Status>
The document status changes once the CEN approval process for the documentation is completed,
Do we use this as the trigger for the status in the XSD changing as well?

2021-03-09 08:54 UTC, tim-rivett approved these changes

2021-03-12 15:38 UTC, merged