CR 083 AffectedSection/AffectedRoute extension
SIRI-CEN/SIRI pull request #68
Opened 2020-12-01 07:39 UTC by prirey

2020-12-04 15:31 UTC, Ulf9 requested changes
[siri_situationAffects-v2.0.zip](https://github.com/SIRI-CEN/SIRI/files/5643607/siri_situationAffects-v2.0.zip)
I made some small corrections to annotation and also cardinality-adjustments on intermediateStopPointRef/StopLaceRef/QuayRef. Please see updated attached file.

2020-12-14 06:24 UTC, prirey commented
Thanks Ulf for the additions!

2021-01-15 07:17 UTC, Ulf9 approved these changes

2021-02-02 11:23 UTC, hennoit approved these changes

2021-03-12 11:12 UTC, haeckerbaer approved these changes

2021-03-12 11:15 UTC, merged